[package]
name = "feiyu-desktop"
version = "1.0.0"
description = "一个漂亮得不像实力派的在线视频播放器 ✨"
authors = ["Del.Wang"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-os = "2.0.0-beta.2"
tauri-plugin-http = "2.0.0-beta.2"
tauri-plugin-shell = "2.0.0-beta.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.36.0", features = ["macros"] }
once_cell = "1.19.0"
reqwest = "0.11.26"
